### PR TITLE
Routing engine

### PR DESCRIPTION
**Pull request by jacted**
Adding routing engine.

### CODE REVIEW

**Comment by bobdesaunois** [comment]
I've reviewed the routing engine but either I seem to be doing wrong or something about the engine isn't going correctly.

I have enabled my Rewrite Module and set AllowOverride to All.
I have taken the liberty of doing some exploration inside the code and found that 
when `Router::dispatch ()` is called by the core after all files have been loaded in it always seems to return `false`.
 It also always brings up the error "Couldn't find that route".

I hope you could clarify what I might not be doing correctly or whether something didn't go as planned.

**Comment by jacted** [comment]
Could you try to add:
"RewriteBase /"
Below "RewriteEngine on" in your .htaccess file.

**Comment by Emerza** [comment]
hey joh
doe is niet

2015-11-26 10:29 GMT+01:00 jacted <notifications@github.com>:

**Comment by bobdesaunois** [comment]
I have done this, my .htaccess file now looks like this:

```
RewriteEngine On
RewriteBase /

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

RewriteRule ^(.*)$ index.php?/$1 [L]
```

**Comment by jacted** [comment]
Can you try to dump this: 
parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
and show results here.

Also what's the path for the framework?
Running it on: localhost/emmaphp/ ?

**Comment by Emerza** [comment]
Stop met al die emails man

**Comment by jacted** [comment]
Comitted a new change that should fix subdir urls.
Can you try the new version.

**Comment by bobdesaunois** [comment]
After having tested the new version everything works accordingly and has been pulled. :) +1

**Pull request merged**
